### PR TITLE
DNM: feat: add ics-20 token transfer support for Penumbra & implement example test cases

### PR DESCRIPTION
**Pull request by jtieri**
## Description
This PR adds support for performing ics-20 token transfers to/from Penumbra in `interchaintest`. 

To add this feature we had to wait for several fixes upstream in the Penumbra repo to rectify some discrepancies in their Proto files and the expected API we rely on in `interchaintest`. This means that we had to perform several upgrades to the Penumbra version, as well as the associated CometBFT version, before we could fully achieve ics-20 support in `interchaintest`.

## How to test

```bash
$ go test -v -race ./examples/penumbra/penumbra_ibc_test.go
```

### CODE REVIEW

**Comment by jackzampolin** [comment]
can we close this PR?

**Comment by jtieri** [comment]
> can we close this PR?

this is the long running PR to add support for `pclientd` and Penumbra IBC. we have been blocked on issues related to timeouts and are still waiting for the Penumbra team to have bandwidth to help dig into the issue. 

we could just get this merged and deal with the timeouts bug later. i can handle the conflicts and get @Reecepbcups to review this next week?

**Comment by Reecepbcups** [comment]
Yes, happy to review next week

**Comment by jtieri** [comment]
The Penumbra team finished adding some additional fixes that were necessary to get the timeout test cases working properly. That work was completed in a separate branch that was rebased on top of the work capture here and can be found in #1157.

Closing this out in favor of that PR instead

**Pull request closed without merging**
