### PR TITLE
lint interchaintest in the same manner as ibc-go

### PR DESCRIPTION
**Pull request by faddat**
This PR lints interchaintest in the same manner as ibc-go for consistency. 

Where exclusions have been made, they've been noted in .golangci.yml.

This is somewhat pursuant to #713, but I think that'll require a second separate PR. 

The goal is to add enforced consistency to the ibc-go codebase.

### CODE REVIEW

**Comment by faddat** [comment]
@boojamya -- this PR and #696 have showed some odd behavior, is it possible that there is a "flaky test" situation or such? 

Basically with #696 I was able to observe some failures, that I think shouldn't have been failures.  Happy to help troubleshoot.

**Comment by boojamya** [comment]
Yes, there are some flaky tests here. Especially that SQL unit test : (

Re-running the test now. 

Also, can you add context here? Is this automated?
We maintain `n` and `n-1` versions of ibc-go, so we'll want to mimic this on our [v6](https://github.com/strangelove-ventures/interchaintest/tree/v6) branch. 

We may also want to add a note to the docs incase external contributes get hung up on linting errors and how to solve.

**Comment by faddat** [comment]
> We maintain n and n-1 versions of ibc-go, so we'll want to mimic this on our [v6](https://github.com/strangelove-ventures/interchaintest/tree/v6) branch.

This PR is in preparation for v50, so is it cool if I focus on main (supporting v50) and v7 (supporting sdk47)?

If needed, I can lint v6 tho, just lmk

**Comment by faddat** [comment]
Is this flaky tests, or do you think there's an issue in the PR?

Thanks

**Comment by Reecepbcups** [comment]
@faddat just flakey

**Comment by Reecepbcups** [comment]
Going to close this as stale due to the # of conflicts & time the PR has been open.

The team has discussed re-opening in the future, but likely should be done from scratch once we agree on which options to use

**Pull request closed without merging**
