### PR TITLE
feat: optionally control other validators from local-ic

### PR DESCRIPTION
**Pull request by Reecepbcups**
Setting a node index (optional, default 0) lets you control another validator via Local Interchain. Example below

```
use node 0
MAKE_REQUEST POST '{"chain_id":"localjuno-1","node_index":0, "action":"bin","cmd":"keys add testKey1 --keyring-backend=test"}'

# default node uses 0
MAKE_REQUEST POST '{"chain_id":"localjuno-1", "action":"bin","cmd":"keys list --keyring-backend=test"}' # default is 0

# interact with node 1
MAKE_REQUEST POST '{"chain_id":"localjuno-1","node_index":1, "action":"bin","cmd":"keys add testKey1 --keyring-backend=test"}'
MAKE_REQUEST POST '{"chain_id":"localjuno-1","node_index":1, "action":"bin","cmd":"keys list --keyring-backend=test"}'

# interact with a node that does not exist
MAKE_REQUEST POST '{"chain_id":"localjuno-1","node_index":999, "action":"bin","cmd":"keys list --keyring-backend=test"}' # fails
## ----
```

### CODE REVIEW

**Comment by Reecepbcups** [comment]
Github has been changing networking recently with actions, and seems they may have broke my approach to background processes.

**Comment by Reecepbcups** [comment]
ref: https://github.com/moby/moby/issues/46129

gRPC is dying in the background with `grpc dial: failed to build resolver: passthrough: received empty target in Build()`

**Comment by Reecepbcups** [comment]
ahh, phew

**Review by jtieri — APPROVED** [review]
this seems super useful! everything looks good to me

**Pull request merged**
