### PR TITLE
feat!: update hermes config

### PR DESCRIPTION
**Pull request by rootulp**
Closes https://github.com/strangelove-ventures/interchaintest/issues/1063

## Testing

I used this patch locally and got past the error mentioned in the issue but I'm not 100% sure everything is resolved yet b/c my test is failing on something else

### CODE REVIEW

**Comment by rootulp** [comment]
It looks like this was fixed in more recent release branches via https://github.com/strangelove-ventures/interchaintest/pull/716 but not on v6

**Comment by Reecepbcups** [comment]
```
           	failed to configure relayer r for chain gaia-9: exit code 1:  The Hermes configuration file at path '/home/hermes/.hermes/config.toml' is invalid, reason: parse error: unknown field `event_source`, expected one of `id`, `type`, `rpc_addr`, `websocket_addr`, `grpc_addr`, `rpc_timeout`, `account_prefix`, `key_name`, `key_store_type`, `store_prefix`, `default_gas`, `max_gas`, `gas_adjustment`, `gas_multiplier`, `fee_granter`, `max_msg_num`, `max_tx_size`, `clock_drift`, `max_block_time`, `trusting_period`, `unbonding_period`, `memo_prefix`, `sequential_batch_tx`, `proof_specs`, `trust_threshold`, `gas_price`, `packet_filter`, `address_type`, `extension_options` for key `chains` at line 63 column 1
  ```
  
  Assume the hermes docker image version needs to be updated as well

**Review by Reecepbcups — APPROVED** [review]

**Comment by rootulp** [comment]
😆 
```
--- FAIL: TestCollector_Stop (0.00s)
    collect_test.go:160: 
        	Error Trace:	/home/runner/work/interchaintest/interchaintest/internal/blockdb/collect_test.go:160
        	Error:      	"6" is not greater than "6"
        	Test:       	TestCollector_Stop
```
will retry unit tests

**Comment by Reecepbcups** [comment]
@mergifyio backport main

**Comment by Reecepbcups** [comment]
@mergifyio backport v7

**Pull request merged**
