### PR TITLE
Merge branch 'main' into feat/hyperspace

### PR DESCRIPTION
**Pull request by anhductn2001**

### CODE REVIEW

**Comment by misko9** [comment]
Merge looks good! Thanks! But the hyperspace test isn't working now because of a change from main so we're looking into it. It is looking like we need to re-populate the user when creating the container and are checking whether this is a viable solution for all docker images.

**Comment by anhductn2001** [comment]
My container can't connect to parachain. So well if you know...
image

**Comment by misko9** [comment]
That still didn't work for me. I will go ahead and merge this in and update the UidGid that is actually built into the container.

**Comment by misko9** [comment]
Please pull the latest and give that a try! Thanks!

**Comment by anhductn2001** [comment]
Ok @misko9. I am trying now. Thank you!

**Comment by anhductn2001** [comment]
image

**Comment by anhductn2001** [comment]
All relay node be exited because the permission. I tried change uidgid !

**Comment by anhductn2001** [comment]
Oh. It worked for me!

**Comment by anhductn2001** [comment]
Oh. It worked for me!

**Comment by anhductn2001** [comment]
image
But faucet amount not equal ...

**Comment by anhductn2001** [comment]
Seem like we should consider GetBalance() and GetAddress() logic. I don't know why have 7766279631452241920 in faucet amount
image

**Comment by anhductn2001** [comment]
image

Have you test func MintFund? I see this err. So good if you know!

**Comment by misko9** [comment]
Composable changed the api for getting ibc balance from their pallet, so I expect a little work there. I'm not familiar with TestBanksyPicassoIBCTransfer test. The mint funds method is working in TestHyperspace.

**Pull request merged**
