### PR TITLE
chore: improvements to `v4-ics` branch

### PR DESCRIPTION
**Pull request by johnletey**

### CODE REVIEW

**Review by Reecepbcups — APPROVED** [review]

**Comment by boojamya** [comment]
Should we upstream to the `v7` branch?

**Comment by Reecepbcups** [comment]
@boojamya This can be upstreamed to your `v7-ics` branch, but only the hermes changes to `v7` base

(I guess a backport to both, then undo it for the `v7`)

**Comment by boojamya** [comment]
@Reecepbcups `v7` includes ics. There is no separate branch. 

There is a separate branch for `v4` and `v4-ics` because the sdk hadn't started including ics in their main branch line yet. 

So we should be able to get away upstreaming to v7.

**Comment by Reecepbcups** [comment]
Sweet

**Comment by boojamya** [comment]
@Mergifyio backport main

**Pull request merged**
