### PR TITLE
chore(deps): update libp2p dependency for v6 branch

### PR DESCRIPTION
**Pull request by MalteHerrmann**
This PR removes the outdated [libp2p/go-libp2p-core](https://github.com/libp2p/go-libp2p-core) dependency from the v6 branch and updates it to use the [go-libp2p](https://github.com/libp2p/go-libp2p) package. This aligns the behaviour with `main` as well and solves dependency issues for us when integrating with the `interchaintest` repo.

### CODE REVIEW

**Comment by boojamya** [comment]
Hey @MalteHerrmann , thanks for this PR!
I'm going to close this out because we plan on tackling https://github.com/strangelove-ventures/interchaintest/issues/539 this sprint. 

If the main branch has the correct version of `go-libp2p`, then that will be part of the up and coming new v6. If not, feel free to point a PR to `main`. 

We should have all the branches in sync here soon!

**Comment by MalteHerrmann** [comment]
@boojamya thanks for the pointer - yes, `main` has the correct dependency, but I was hoping we could get this merged ASAP because it's blocking us from using the repo for testing in a straight forward way :v:

If not, we can work around it for now I guess

**Review by boojamya — APPROVED** [review]

**Comment by boojamya** [comment]
Noted! Then lets get this in there.

**Comment by MalteHerrmann** [comment]
Thanks a lot @boojamya! Appreciate it 🙏

**Pull request merged**
