### PR TITLE
Update WASMD

### PR DESCRIPTION
**Pull request by faddat**
- update wasmd to the latest release from confio.

Please note that this pull request no longer makes any changes to the version of go used by this repository, many thanks to @boojamya and @sontrinh16 for pointers on that.

### CODE REVIEW

**Review by boojamya — CHANGES_REQUESTED** [review]
As stated here: https://github.com/strangelove-ventures/interchaintest/pull/695#issuecomment-1677420805, we think it is too soon to update to Go `1.21`. 

Could you remove the Go upgrade from this PR?

**Comment by faddat** [comment]
Very happy to, thanks for the note!

**Comment by faddat** [comment]
@boojamya hey, I think go 1.21 might've been what made this pass ci?

I am not sure of this, but check out:

https://github.com/strangelove-ventures/interchaintest/pull/696/commits/9d8c2c5c92995593e69f5d20c491426fef5628f1

**Comment by faddat** [comment]
I'm just going to try using 1.21 again, to check.

**Comment by faddat** [comment]
@boojamya -- I have a feeling that go v1.21.x is what makes this one work.  I can't say precisely why, but do see fairly large changes in go.sum.

**Comment by sontrinh16** [comment]
> @boojamya -- I have a feeling that go v1.21.x is what makes this one work. I can't say precisely why, but do see fairly large changes in go.sum.
> 
> If you've other suggestions, I'm all ears.

hey i think when you update go version in go mod file you haven't update go version in the CI script as you can see here [https://github.com/faddat/ibctest/blob/271ae9e4a8a3004de48ca0716c882027c79d9c43/.github/workflows/e2e-tests.yml#L20](url)

**Comment by faddat** [comment]
@sontrinh16 thank you!

I'll uptate ci, but I guess this just compounds the question of why it works with v1.21 but not v1.20.

**Comment by faddat** [comment]
@sontrinh16 are you referring to reverting back to 1.19?

If you think it will work please feel free to open a PR with this code and moving back to 1.19.  I guess it is possible that we hit a compatibility issue.

**Comment by faddat** [comment]
Going to try and take all of this back to 1.19.

**Comment by sontrinh16** [comment]
> @sontrinh16 thank you!
> 
> I'll uptate ci, but I guess this just compounds the question of why it works with v1.21 but not v1.20.

i think because it is using go 1.21 but the go mod file is using go 1.20 so it fail

**Comment by faddat** [comment]
@sontrinh16 seems to me that it really is the go version. 

....which doesn't make a lot of sense.

**Comment by faddat** [comment]
Hey, wait -- yeah, we've flaky tests somewhere.  

Evidence: this PR.  Check out a few commits up, everything worked.  Nothing else really changed, but sometimes we pass and sometimes we fail.

**Review by boojamya — APPROVED** [review]
Nice. Thanks guys!

**Pull request merged**
